# Generated by Django 3.1 on 2022-08-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'slider', 'verbose_name_plural': 'slideres'},
        ),
    ]
