# Generated by Django 3.1 on 2022-05-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Paypal', 'Paypal'), ('SSLCommerz', 'SSLCommerz')], default='Cash On Delivery', max_length=50),
        ),
    ]
